name: torchswe-cmake
channels:
  - conda-forge
  - defaults
dependencies:
  # original dependencies from TorchSWE, with versions removed

  - _libgcc_mutex
  - _openmp_mutex
  - _sysroot_linux-64_curr_repodata_hack
  - abseil-cpp
  - alsa-lib
  - aom
  - appdirs
  - argon2-cffi
  - argon2-cffi-bindings
  - arrow-cpp
  - astroid
  - asttokens
  - attrs
  - aws-c-cal
  - aws-c-common
  - aws-c-event-stream
  - aws-c-io
  - aws-checksums
  - aws-sdk-cpp
  - backcall
  - backports
  - backports.functools_lru_cache
  - beautifulsoup4
  # - binutils  # this creates the ld symlink
  - binutils_impl_linux-64
  - binutils_linux-64
  - bleach
  - brotli
  - brotli-bin
  - bzip2
  - c-ares
  # - c-compiler
  - ca-certificates
  - cached-property
  - cached_property
  - certifi
  - cffi
  - cfgv
  - cftime
  # - clang  # some issue with clang
  # - clang-13
  # - clang-format
  # - clang-format-13
  # - clang-tools
  - cmake
  - colorama
  - coverage
  - cudatoolkit=11.3  # specific version here
  - cudnn
  - cupy
  - curl
  - cutensor
  # - cxx-compiler
  - cycler
  - dbus
  - debugpy
  - decorator
  - defusedxml
  - dill
  - distlib
  - distro
  - double-conversion
  - eigen
  - entrypoints
  - executing
  - expat
  - fastrlock
  - ffmpeg
  - filelock
  - flake8
  - flit-core
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fonttools
  - freetype
  # - gcc  # this creates the gcc symlink
  - gcc_impl_linux-64
  # - gcc_linux-64  # this sets $CC
  - gettext
  - gflags
  - giflib
  - gl2ps
  - glew
  - glib
  - glib-tools
  - glog
  - gmp
  - gnutls
  - grpc-cpp
  - gst-plugins-base
  - gstreamer
  # - gxx  # this creates the g++ symlink
  - gxx_impl_linux-64
  # - gxx_linux-64  # this sets $CXX
  - h5py
  - hdf4
  - hdf5
  - icu
  - identify
  - imageio
  - importlib-metadata
  - importlib_resources
  - iniconfig
  - ipycanvas
  - ipyevents
  - ipykernel
  - ipython
  - ipython_genutils
  - ipyvtklink
  - ipywidgets
  - isort
  - jbig
  - jedi
  - jinja2
  - jpeg
  - jsoncpp
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyterlab_pygments
  - jupyterlab_widgets
  - kernel-headers_linux-64
  - keyutils
  - kiwisolver
  - krb5
  - lame
  - lazy-object-proxy
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcbor
  - libclang
  - libclang-cpp13
  - libcrc32c
  - libcurl
  - libdeflate
  - libdrm
  - libedit
  - libev
  - libevent
  - libffi
  - libfido2
  - libgcc-devel_linux-64
  - libgcc-ng
  - libgfortran-ng
  - libgfortran5
  - libglib
  - libglu
  - libgomp
  - libgoogle-cloud
  - libiconv
  - liblapack
  - libllvm13
  - libnetcdf
  - libnghttp2
  - libnsl
  - libogg
  - libopenblas
  - libopus
  - libpciaccess
  - libpng
  - libpq
  - libprotobuf
  - libsanitizer
  - libsodium
  - libssh2
  - libstdcxx-devel_linux-64
  - libstdcxx-ng
  - libtheora
  - libthrift
  - libtiff
  - libudev1
  - libutf8proc
  - libuuid
  - libuv
  - libva
  - libvorbis
  - libvpx
  - libwebp
  - libwebp-base
  - libxcb
  - libxkbcommon
  - libxml2
  - libzip
  - libzlib
  - llvm-openmp
  - loguru
  - lz4-c
  - make
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mccabe
  - mistune
  - mock
  # - mpi
  # - mpi4py
  - munkres
  - mypy
  - mypy_extensions
  - mysql-common
  - mysql-libs
  - nbclient
  - nbconvert
  - nbconvert-core
  - nbconvert-pandoc
  - nbformat
  - nccl
  - ncurses
  - nest-asyncio
  - netcdf4
  - nettle
  - ninja
  - nodeenv
  - notebook
  - nspr
  - nss
  - numpy
  - openblas
  - openh264
  - openjpeg
  # - openmpi
  - openssh
  - openssl
  - opt-einsum
  - orc
  - orjson
  - packaging
  - pandoc
  - pandocfilters
  - parquet-cpp
  - parso
  - pcre
  - pexpect
  - pickleshare
  - pillow
  - pip
  - platformdirs
  - pluggy
  - pre-commit
  - proj
  - prometheus_client
  - prompt-toolkit
  - prompt_toolkit
  - psutil
  - pthread-stubs
  - ptyprocess
  - pugixml
  - pure_eval
  - py
  - pyarrow
  - pycodestyle
  - pycparser
  - pydantic
  - pyflakes
  - pygments
  - pylint
  - pynvml
  - pyparsing
  - pyqt
  - pyqt-impl
  - pyqt5-sip
  - pyqtchart
  - pyqtwebengine
  - pyrsistent
  - pytest
  - pytest-cov
  - pytest-lazy-fixture
  - pytest-mock
  - python=3.9  # specific version here
  - python-dateutil
  - python-fastjsonschema
  - python_abi
  - pyvista
  - pyyaml
  - pyzmq
  - qt
  - qtconsole
  - qtconsole-base
  - qtpy
  - re2
  - readline
  - rhash
  - s2n
  - scikit-build
  - scipy
  - scooby
  - send2trash
  - setuptools
  - six
  - snappy
  - soupsieve
  - sqlite
  - stack_data
  - svt-av1
  - sysroot_linux-64
  - tbb
  - tbb-devel
  - terminado
  - tinycss2
  - tk
  - toml
  - tomli
  - tornado
  - traitlets
  - types-docutils
  - typing-extensions
  - typing_extensions
  - tzdata
  - ucx
  - ukkonen
  - unicodedata2
  - utfcpp
  - virtualenv
  - vtk
  - wcwidth
  - webencodings
  - wheel
  - widgetsnbextension
  - wrapt
  - x264
  - x265
  - xorg-fixesproto
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxfixes
  - xorg-libxt
  - xorg-xextproto
  - xorg-xproto
  - xz
  - yaml
  - zeromq
  - zipp
  - zlib
  - zstd
  - pip:
    - alabaster
    - babel
    - charset-normalizer
    - commonmark
    - docutils
    - idna
    - imagesize
    - markdown
    - pydata-sphinx-theme
    - pytz
    - recommonmark
    - requests
    - snowballstemmer
    - sphinx
    - sphinx-copybutton
    - sphinx-markdown-tables
    - sphinxcontrib-applehelp
    - sphinxcontrib-devhelp
    - sphinxcontrib-htmlhelp
    - sphinxcontrib-jsmath
    - sphinxcontrib-qthelp
    - sphinxcontrib-serializinghtml
    - tifffile
    - urllib3

  # from cunumeric's env file

  # cuda
  - cudatoolkit=11.3
  - cutensor>=1.3.3
  - nccl
  - pynvml

  # build
  - cmake>=3.24,!=3.25.0
  - git
  - make
  - scikit-build>=0.13.1
  - setuptools>=60
  - zlib

  # runtime
  - cffi
  - llvm-openmp
  - numpy>=1.22
  - openblas=*=*openmp*
  - opt_einsum
  - pyarrow>=5
  - scipy
  - typing_extensions

  # tests
  # - clang-tools>=8
  # - clang>=8
  - colorama
  - coverage
  - mock
  - mypy>=0.961
  - pre-commit
  - pytest-cov
  - pytest-lazy-fixture
  - pytest-mock
  - pytest
  - types-docutils

  - pip
  - pip:
    # tests
    - tifffile

    # docs
    - jinja2
    - markdown<3.4.0
    - pydata-sphinx-theme
    - recommonmark
    - sphinx-copybutton
    - sphinx-markdown-tables
    - sphinx>=4.4.0
